---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgDGnP2YkHHizWT4SIPwan6lkRME7cWTipawKRfikn2p1LPXMzR79Pn4VhqAcZu829PBXoU3SLSFtxnXg98wuujY0a/IsZByrUBSKRXpEzshmsDa1u0Kj3OU7PPB8ml5EMgBczCEtkVz+qSpEKRgaVMr4ASh1jifs3CXMpz09hepe8zywYXWGgNqQ+EWNUrVqjwTF8vujb2O4FL3ReceJp2NBlio+xzuRGzVvv4i7zsvc4hxAx3pYMW46KNtS+1Kd6+pfxpR0HQKP9x99zbritVf+gUs3aQT23H+47oWrFziBcUkj3DRONkFIBUsEQuonV4x6D0Mutz9Q25cjX5wzDOaNyYFPisVGHdLqHgaZUcS0r1S/qAIoboysbKqTN2HG08aCwebcNxkgD3q11rrm1R+BChbWmkkddrHlbP+wFi5/SFQhTaQk+ZthBthSgRnGvuS511mgWnLMxrFfDJh2qeUjR5AFP35qvbGPy5hRuPCIJHg3cKbI+EdunZJUdJ3FeROFcqQCgTaokgYDeBdy5Ytu6oCsx1NK+X9lE/woIWz9aajMpFLrxzZKQ290wQF4FMcImAPtkCU8RqdoWUXy+Hcd+gXNdsWyCSaqryblhMDEVbf6twOpha/m0hazMFtl+GAq7rdUwkeELSi2c1cAn3GcPpRKQSmibC3JPkHmLNYljQHGjM7iq6UoQMmup4EqIf1D7u4FGY7q+eZp/miRvh+/dJoenXBnQU=
    token: AgAu/pC5u6MerGhvUox+Rzb81NrNxkKiwC6I6QHRlSPB5m8kcdlCSuoWOuPPh8Fp7ibcnIVLfpCkyLjsQhVOo5NZQkwfAGeDs/p5riuId6NaiC9s2Knlv9tOGfTfb5jyGWSQwlBQMbe05ra9zUlt3EVFqcpf8fBQb+pWyO/vy3A3glVVp3J8vlkOB2w2w+/CnVsNDiUFrfLcXXNrilVW5KKWN/4Zcf79+gz8JCQn53gkRfu8/I/bPsiTlV9JmqP+VoR+AhyjiGmv17iPSbb2VVzJDfYoInZpP3sqYrfIC8AlECyqYL2KzDn/uUzG6SOMSNyMWXPS4d/Y3AcRJci43Sd5+95WW+EBcacmqrBAyvJbIWlpu6ocpeeyWqvc1rTjJCbk7W1yQ/15iO38yYP6kczl4pU0UKP3WqVH6XIdZGAi27czSD0AyxlUri8y/m0b9dgbZ/dlGCs08sXphwgcWe2zx1LN2kCTAkzK82vlEtTMWmTrUKeDlBlEpmCYbf1DiF8MZwPf6Zzsve5gxPiDvovhDDl5Ko5QlUngzo8Ry36YVeslDzxWB8tH0KJvvv7biaNbHWRDwnkqscS2ky2/qt8URVm1ay2sLxf6MzIl18luf9FWcxmWUVV/hCBbDUXPOY9OMiWFr47saroaE5MX947LbUx3NApFV8WRcD/NB8ngyXGRO3LIEHThd2iciuF270BVNNr0vmdYSrEXBfzP4vt7tNP/Skivz23q10EC7vOyNlqo0WjL9vAMw4VTETIsUUScC2mlHJ/ddQfOXSkQfy7x
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-admin
      namespace: monitoring
